import { Raleway, Open_Sans } from "next/font/google";
import "/public/globals.css";
import Topbar from "@/components/User/Topbar";

const raleway = Raleway({
  subsets: ["latin"],
  weight: ["400", "700"], // Pilih variasi berat font yang diinginkan
  variable: "--font-raleway",
});

const openSans = Open_Sans({
  subsets: ["latin"],
  weight: ["400", "600"], // Pilih variasi berat font yang diinginkan
  variable: "--font-open-sans",
});

export const metadata = {
  title: "PKPA - Learning Management System",
  description: "Generated by PKPA - Learning Management System",
};

export default function Course({ children }) {
  return (
    <html lang="en" className={`${raleway.variable} ${openSans.variable}`}>
      <body className="bg-gray-100">
        <Topbar />
        <div>
          <main>{children}</main>
        </div>
      </body>
    </html>
  );
}
