
import { Raleway, Open_Sans } from "next/font/google";
import "../globals.css"

const raleway = Raleway({
  subsets: ["latin"],
  weight: ["400", "700"], // Pilih variasi berat font yang diinginkan
  variable: "--font-raleway",
});

const openSans = Open_Sans({
  subsets: ["latin"],
  weight: ["400", "600"], // Pilih variasi berat font yang diinginkan
  variable: "--font-open-sans",
});

export const metadata = {
  title: "PKPA - Learning Management System",
  description: "Generated by PKPA - Learning Management System",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${raleway.variable} ${openSans.variable}`}>
      <head></head>
      <body>{children}</body>
    </html>
  );
}

