import { Raleway, Open_Sans } from "next/font/google";
import Sidebar from "@/components/User/sidebar";
import "/public/globals.css";
import Navbar from "@/components/User/navbar";

const raleway = Raleway({
  subsets: ["latin"],
  weight: ["400", "700"], // Pilih variasi berat font yang diinginkan
  variable: "--font-raleway",
});

const openSans = Open_Sans({
  subsets: ["latin"],
  weight: ["400", "600"], // Pilih variasi berat font yang diinginkan
  variable: "--font-open-sans",
});

export const metadata = {
  title: "PKPA - Learning Management System",
  description: "Generated by PKPA - Learning Management System",
};

export default function MataKuliah({ children }) {
  return (
    <html lang="en" className={`${raleway.variable} ${openSans.variable}`}>
      <body className="bg-gray-100">
        <Navbar />
        <div className="flex min-h-screen mt-8 mx-16">
          <Sidebar />
          <main className="flex-1 px-8">{children}</main>
        </div>
      </body>
    </html>
  );
}
